apiVersion: v1
kind: Service
metadata:
  name: exercise-python-service
spec:
  selector:
    app: exercise-python-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30443
  type: NodePort
